name: release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish:
    uses: Codillas/terraform-provider-koyeb/.github/workflows/release-publish.yml@main
    secrets: inherit
